cc_test(
    name = "channel_test",
    srcs = ["channel_test.cpp"],
    deps = [
        "//src:gaia_net",
    ]
)

cc_test(
    name = "channel_bench",
    srcs = ["channel_bench.cpp"],
    deps = [
        "//src:gaia_net",
    ]
)

cc_test(
    name = "connect_test",
    srcs = ["connect_test.cpp"],
    deps = [
        "//src:gaia_net",
    ]
)

cc_test(
    name = "redis_test",
    srcs = ["redis_test.cc"],
    deps = [
        "@com_google_googletest//:gtest_main",
    ]
)

cc_test(
    name = "test_grpc_memleak",
    srcs = ["test_grpc_memleak.cpp"],
    deps = [
        "//src:gaia_net",
    ]
)

cc_test(
    name = "util_test",
    srcs = ["util_test.cc"],
    deps = [
        "//src:gaia_net",
    ]
)
